from abc import ABC, abstractmethod
from typing import Any
from uuid import UUID


class ProposalRepositoryPort(ABC):
    """
    Abstract port defining the persistence contract for proposal generation requests.
    All concrete adapters (MySQL, in-memory) must implement this interface.
    """

    @abstractmethod
    def create_request(
        self,
        request_id: UUID,
        raw_requirements: str,
        client_name: str | None,
    ) -> None:
        """
        Persists a new proposal generation request in 'pending' status.
        The request_id is generated at the application layer (UUID v4).
        """
        ...

    @abstractmethod
    def get_request_by_id(self, request_id: UUID) -> dict[str, Any] | None:
        """
        Retrieves a request record by its UUID.
        Returns a dict with all fields or None if not found.
        """
        ...

    @abstractmethod
    def update_request_status(
        self,
        request_id: UUID,
        status: str,
        current_node: str | None = None,
        error_message: str | None = None,
        llm_provider_used: str | None = None,
    ) -> None:
        """
        Updates the lifecycle state of a request.
        Called by each agent node as the pipeline progresses.
        """
        ...

    @abstractmethod
    def save_proposal(
        self,
        request_id: UUID,
        proposal_id: UUID,
        clean_requirements: list[str],
        identified_ambiguities: list[dict[str, Any]],
        resolved_assumptions: list[str],
        suggested_tech_stack: dict[str, str],
        proposed_modules: list[dict[str, Any]],
        total_estimated_hours: int,
        final_markdown: str,
    ) -> None:
        """
        Persists the final proposal generated by the Writer Agent.
        Also updates the associated request status to 'completed'.
        """
        ...


class AgentLogRepositoryPort(ABC):
    """
    Abstract port defining the persistence contract for agent execution audit logs.
    A log row is inserted after each LangGraph node completes (success or error).
    """

    @abstractmethod
    def save_agent_log(
        self,
        request_id: UUID,
        node_name: str,
        status: str,
        input_state_snapshot: dict[str, Any] | None = None,
        output_state_snapshot: dict[str, Any] | None = None,
        execution_time_ms: int | None = None,
        tokens_used_estimate: int | None = None,
        error_trace: str | None = None,
    ) -> None:
        """
        Persists an audit record for a single LangGraph node execution.
        """
        ...
