from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, ForeignKey, Index, Integer, String, func
from sqlalchemy.dialects.mysql import JSON, LONGTEXT
from sqlalchemy.orm import Mapped, mapped_column

from app.domain.models.base import Base


class Proposal(Base):
    """
    ORM model for the 'proposals' table.
    Stores the consolidated final result generated by the Writer Agent.
    Has a 1:1 relationship with the 'requests' table.
    """

    __tablename__ = "proposals"
    __table_args__ = (
        Index("uq_proposals_request_id", "request_id", unique=True),
        {"mysql_charset": "utf8mb4", "mysql_collate": "utf8mb4_unicode_ci"},
    )

    # UUID v4 generated at the application layer
    id: Mapped[str] = mapped_column(String(36), primary_key=True)

    # Foreign key to the originating request (cascades on delete)
    request_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("requests.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Structured requirements extracted by the Analyst Agent
    clean_requirements_json: Mapped[list[str] | None] = mapped_column(
        JSON, nullable=True
    )

    # List of ambiguities detected by the Analyst Agent
    # Shape: [{"point": str, "question": str}]
    identified_ambiguities_json: Mapped[list[dict[str, Any]] | None] = mapped_column(
        JSON, nullable=True
    )

    # Explicit assumptions used by the Architect Agent to resolve ambiguities
    resolved_assumptions_json: Mapped[list[str] | None] = mapped_column(
        JSON, nullable=True
    )

    # Tech stack proposed by the Architect Agent
    # Shape: {"category": "technology"}
    suggested_tech_stack_json: Mapped[dict[str, str] | None] = mapped_column(
        JSON, nullable=True
    )

    # List of proposed modules with individual hour estimates
    # Shape: [{"name": str, "description": str, "estimated_hours": int}]
    proposed_modules_json: Mapped[list[dict[str, Any]] | None] = mapped_column(
        JSON, nullable=True
    )

    # Total sum of estimated hours across all proposed modules
    total_estimated_hours: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Final Markdown document compiled by the Writer Agent
    final_markdown: Mapped[str | None] = mapped_column(LONGTEXT, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now()
    )
